### ISSUE TITLE
What is the data source?

### ISSUE THREAD

**Issue by stevevance** [wkrause13/miamiTrolleyTracker#2]
Hi, I'm an independent transit data reviewer for Mapzen's Transitland product, an open source database of worldwide GTFS feeds. 

This looks like a great project to give people in Miami greater information about where to catch a ride on transit.

Is there a GTFS feed that you're using to show Miami Trolleys?

**Comment by qtrandev** [comment]
Sorry for the late response - it has been a year since I looked at this.
The data is proprietary by the previous provider Etaspot. The new trolley provider for City of Miami is TSO Mobile, but also proprietary. 

The TSO Mobile website is here (the data can be scraped if the source code is viewed for the API endpoints): 
http://app.tsomobile.com/publictransportation/driverroute.htm?tkn=81E39EC9-D773-447E-BE29-D7F30AB177BC&lan=en

The county, Miami-Dade County does try to publish the data here, but I believe this data is incomplete: https://transitfeeds.com/p/miami-dade-county-transit/48/latest/route/16886

My attempt to list data on all South Florida agencies is here: https://github.com/qtrandev/OneBusAway/wiki/Transit-Agencies

**Comment by stevevance** [comment]
gotcha. I thought it was a separate operator, but the trolley is already included in the Miami-Dade Transit GTFS feed.
